#!/data/data/com.termux/files/usr/bin/bash

# Delete removed mirrors
for f in asia/packages.nscdn.top china/mirrors.dgut.edu.cn china/mirrors.hit.edu.cn china/mirrors.njupt.edu.cn china/mirrors.scau.edu.cn china/mirror.iscas.ac.cn china/mirror.nyist.edu.cn china/mirror.sjtu.edu.cn china/mirrors.aliyun.com china/mirrors.bfsu.edu.cn china/mirrors.cqupt.edu.cn china/mirrors.nju.edu.cn china/mirrors.pku.edu.cn china/mirrors.qvq.net.cn china/mirrors.sau.edu.cn china/mirrors.sdu.edu.cn china/mirrors.sustech.edu.cn china/mirrors.tuna.tsinghua.edu.cn china/mirrors.ustc.edu.cn china/mirrors.zju.edu.cn chinese_mainland/mirrors.qvq.net.cn europe/cdn.lumito.net europe/mirror.termux.dv europe/termux.sahilister.in europe/termux.astra.in.ua north_america/packages.termux.dev oceania/mirrors.wale.id.au russia/mirror.surf south_america/mirrors.rda.run asia/mirrors.saswata.xyz asia/mirrors.omsinchan.ac.th; do
    if test -f "/data/data/com.termux/files/usr/etc/termux/mirrors/$f"; then
        echo "Deleting removed mirror: $f"; rm -f "/data/data/com.termux/files/usr/etc/termux/mirrors/$f";
    fi
done
